"""Fraud Detection Schemas."""

from modules.ai.fraud_detection.schemas.fraud_schemas import (
    # Alert schemas
    FraudAlertCreate,
    FraudAlertUpdate,
    FraudAlertResponse,
    AlertListResponse,
    AlertAssignRequest,
    AlertResolveRequest,
    AlertEscalateRequest,
    AlertFeedbackRequest,
    # Rule schemas
    FraudRuleCreate,
    FraudRuleUpdate,
    FraudRuleResponse,
    RuleCondition,
    RuleTestRequest,
    RuleTestResponse,
    # Pattern schemas
    FraudPatternCreate,
    FraudPatternUpdate,
    FraudPatternResponse,
    PatternMatchRequest,
    PatternMatchResponse,
    # Profile schemas
    RiskProfileCreate,
    RiskProfileUpdate,
    RiskProfileResponse,
    RiskScoreRequest,
    RiskScoreResponse,
    # Detection schemas
    DetectionRequest,
    DetectionResponse,
    TransactionCheckRequest,
    TransactionCheckResponse,
    AccessCheckRequest,
    AccessCheckResponse,
    # Dashboard schemas
    FraudDashboardStats,
    AlertsSummary,
    RiskDistribution,
)

__all__ = [
    "FraudAlertCreate",
    "FraudAlertUpdate",
    "FraudAlertResponse",
    "AlertListResponse",
    "AlertAssignRequest",
    "AlertResolveRequest",
    "AlertEscalateRequest",
    "AlertFeedbackRequest",
    "FraudRuleCreate",
    "FraudRuleUpdate",
    "FraudRuleResponse",
    "RuleCondition",
    "RuleTestRequest",
    "RuleTestResponse",
    "FraudPatternCreate",
    "FraudPatternUpdate",
    "FraudPatternResponse",
    "PatternMatchRequest",
    "PatternMatchResponse",
    "RiskProfileCreate",
    "RiskProfileUpdate",
    "RiskProfileResponse",
    "RiskScoreRequest",
    "RiskScoreResponse",
    "DetectionRequest",
    "DetectionResponse",
    "TransactionCheckRequest",
    "TransactionCheckResponse",
    "AccessCheckRequest",
    "AccessCheckResponse",
    "FraudDashboardStats",
    "AlertsSummary",
    "RiskDistribution",
]
