--
-- PostgreSQL database dump
--

\restrict AEZwISLJ74oMntlv35fzbL0HV5gdghqRoLKIxToYwfwI9pgeaJMu8IVtPaArkKF

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('9bac5ff5-7614-4498-809c-b88c6841672e', 'CLI-0001', 'Conecta Mais - Segurança e Tecnologia', 'Conecta Mais - Segurança e Tecnologia', 'pj', 'cnpj', '00000000000000', NULL, NULL, 'contato@conectamais.pro', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-01-19 01:31:34.733036', '2026-01-19 01:31:34.733036', NULL, NULL, false, false, NULL, NULL, NULL, 'direto', NULL, NULL);
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('b043f21a-97ea-4e53-b78a-2eb0cead9383', 'CLI-0006', 'CONDOMINIO PARQUE RESIDENCIAL GELAIN', 'Condomínio Gelain', 'condominium', 'cnpj', '00736037000182', NULL, NULL, 'gelain@conectamais.pro', NULL, NULL, NULL, NULL, 'Rua Gabriel Gonçalves', '9', 'Bloco A-1', 'Aleixo', 'Manaus', 'AM', '69060-000', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'small', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, false, NULL, NULL, 'f3b5adc0-7833-4481-978f-2282e196bcce', 'converted_lead', 6000.00, '00736037000182');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('a26984e9-a412-4e7e-b4a0-e0d4352856fc', 'CLI-0007', 'CONDOMINIO RESIDENCIAL PARISE VILLAGE', 'Condomínio Parise Village', 'condominium', 'cnpj', '34857941000168', NULL, NULL, 'parisevillage@conectamais.pro', NULL, NULL, NULL, NULL, 'Rua Partenon', '475', NULL, 'Flores', 'Manaus', 'AM', '69058-340', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'small', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, false, NULL, NULL, '4e552098-6703-4759-a21d-63a4acf27b99', 'converted_lead', 1700.00, '34857941000168');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('c0750f70-7e60-4898-9ed2-d303e361c41e', 'CLI-0008', 'CONDOMINIO RESIDENCIAL GREEN HILLS', 'Condomínio Green Hills', 'condominium', 'cnpj', '08063476000183', NULL, NULL, 'greenhills@conectamais.pro', NULL, NULL, NULL, NULL, 'Rua Marques de Suassuna', 'SN', NULL, 'Parque das Laranjeiras', 'Manaus', 'AM', '69058-810', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'small', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, false, NULL, NULL, 'cbdb15c0-87e9-4b79-a2a8-628ebf9ce6bf', 'converted_lead', 500.00, '08063476000183');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('806c4970-ab5a-491a-aa6a-a1aad705234a', 'CLI-0009', 'CONDOMINIO VILLA DEI FIORI', 'Condomínio Villa Dei Fiori', 'condominium', 'cnpj', '02153384000108', NULL, NULL, 'villadei@conectamais.pro', NULL, NULL, NULL, NULL, 'Av. Constantino Nery', 'S/N', NULL, 'Chapada', 'Manaus', 'AM', '69050-001', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'large', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, false, NULL, NULL, 'b1bd8c42-d27a-4447-8816-d433e81b8014', 'converted_lead', 25592.71, '02153384000108');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('e6a18d9f-497d-4d85-922b-3feb153a8af3', 'CLI-0010', 'CONDOMINIO DO EDIFICIO MICHELANGELO', 'Condomínio Michelangelo', 'condominium', 'cnpj', '04911208000113', NULL, NULL, 'michelangelo@conectamais.pro', NULL, NULL, NULL, NULL, 'Rua Paraíba', '1020', NULL, 'Adrianópolis', 'Manaus', 'AM', '69057-021', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'small', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, false, NULL, NULL, '3470aef5-c403-42f3-8351-36d222fd2a16', 'converted_lead', 8346.70, '04911208000113');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('2b17d0f2-06de-4f09-9024-44849263bfe0', 'CLI-0011', 'CONDOMINIO RESIDENCIAL VILLA DOS PASSAROS', 'Condomínio Villa dos Pássaros', 'condominium', 'cnpj', '13221953000121', NULL, NULL, 'villapassaros@conectamais.pro', NULL, NULL, NULL, NULL, 'Rod. Torquato Tapajós', '11265', 'Rodovia AM-10', 'Tarumã', 'Manaus', 'AM', '69041-025', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'large', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, true, NULL, NULL, 'ecff80b2-37b5-4a99-9070-c755b2713814', 'converted_lead', 37338.33, '13221953000121');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('f8e84fa7-0fcc-43d5-8ee3-f3734b410d07', 'CLI-0012', 'CONDOMINIO MIRANTE DAS FLORES', 'Condomínio Mirante das Flores', 'condominium', 'cnpj', '52605708000170', NULL, NULL, 'miranteflores@conectamais.pro', NULL, NULL, NULL, NULL, 'Rua Narciso Cavalcante de Melo', '370', NULL, 'Ponta Negra', 'Manaus', 'AM', '69037-207', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'large', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, true, NULL, NULL, 'b8d821f2-816f-4767-9966-86d4d4ce8f06', 'converted_lead', 42255.80, '52605708000170');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('37f35647-bf2b-488f-9146-a653d205cc77', 'CLI-0013', 'RESIDENCIAL LARANJEIRAS VILLAGE', 'Residencial Laranjeiras Village', 'condominium', 'cnpj', '24632786000128', NULL, NULL, 'ADMLARANJEIRASVILLAGE@GMAIL.COM', NULL, NULL, NULL, NULL, 'Rua Paraopeba', '274', 'CJ B Flor II', 'Flores', 'Manaus', 'AM', '69028-388', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'large', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, true, NULL, NULL, 'b5be0f2d-1938-4404-b196-fe42857eb083', 'converted_lead', 42544.50, '24632786000128');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('f59c7354-1541-4f47-a18b-c25f581bb5eb', 'CLI-0014', 'CONDOMINIO PRIME ARENA', 'Condomínio Prime Arena', 'condominium', 'cnpj', '47405340000166', NULL, NULL, 'PRIME.ARENAA@GMAIL.COM', NULL, NULL, NULL, NULL, 'Rua Parque dos Franceses', '736', NULL, 'Chapada', 'Manaus', 'AM', '69050-045', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'large', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, true, NULL, NULL, '5fbadd7a-cd75-4725-9fbd-a50ac8d4e6c6', 'converted_lead', 40466.50, '47405340000166');
INSERT INTO public.clients (id, code, name, trading_name, client_type, document_type, document_number, state_registration, municipal_registration, email, phone, mobile, whatsapp, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, billing_address_street, billing_address_number, billing_address_complement, billing_address_neighborhood, billing_address_city, billing_address_state, billing_address_zipcode, financial_contact_name, financial_contact_email, financial_contact_phone, technical_contact_name, technical_contact_email, technical_contact_phone, status, segment, contract_start_date, contract_end_date, first_billing_date, last_billing_date, credit_limit, payment_terms, billing_day, total_revenue, total_debt, health_score, satisfaction_score, engagement_score, guardian_enabled, plus_enabled, guardian_client_id, plus_client_id, notes, tags, metadata, account_manager_id, sales_rep_id, ativo, created_at, updated_at, created_by, updated_by, is_defaulter, is_vip, default_since, default_amount, lead_id, crm_origin, mrr, pix_key) VALUES ('003197ed-2e49-45aa-80a8-3e837c9d1404', 'CLI-0015', 'CONDOMINIO IDEAL FLORES DA CIDADE', 'Condomínio Ideal Flores da Cidade', 'condominium', 'cnpj', '23147782000191', NULL, NULL, 'idealflores@conectamais.pro', NULL, NULL, NULL, NULL, 'Rua Franz Schubert', '840', NULL, 'Flores', 'Manaus', 'AM', '69028-331', 'Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', 'enterprise', NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, false, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, '2026-03-23 02:46:58.706735', '2026-03-23 02:46:58.706735', NULL, NULL, false, true, NULL, NULL, 'ea23da54-efa9-40e8-b4df-dfd6d2962d03', 'converted_lead', 65842.42, '23147782000191');


--
-- PostgreSQL database dump complete
--

\unrestrict AEZwISLJ74oMntlv35fzbL0HV5gdghqRoLKIxToYwfwI9pgeaJMu8IVtPaArkKF
