"""Schemas do módulo de Moradores."""

from modules.residents.schemas.resident import (
    ResidentBase,
    ResidentCreate,
    ResidentUpdate,
    ResidentResponse,
    ResidentBlock,
    ResidentSetDefaulter,
    ResidentMoveOut,
    ResidentTransferUnit,
    ResidentEnableAccess,
    ResidentFilter,
    ResidentListResponse,
    ResidentStats,
    ResidentSearch,
)
from modules.residents.schemas.vehicle import (
    VehicleBase,
    VehicleCreate,
    VehicleUpdate,
    VehicleResponse,
    VehicleBlock,
    VehicleAssignParking,
    VehicleFilter,
    VehicleListResponse,
    VehicleStats,
)
from modules.residents.schemas.pet import (
    PetBase,
    PetCreate,
    PetUpdate,
    PetResponse,
    PetUpdateVaccination,
    PetFilter,
    PetListResponse,
    PetStats,
)
from modules.residents.schemas.dependent import (
    DependentBase,
    DependentCreate,
    DependentUpdate,
    DependentResponse,
    DependentBlock,
    DependentSetTemporary,
    DependentAddPickupPerson,
    DependentFilter,
    DependentListResponse,
    DependentStats,
)
from modules.residents.schemas.emergency_contact import (
    EmergencyContactBase,
    EmergencyContactCreate,
    EmergencyContactUpdate,
    EmergencyContactResponse,
    EmergencyContactFilter,
    EmergencyContactListResponse,
)

__all__ = [
    # Resident
    "ResidentBase",
    "ResidentCreate",
    "ResidentUpdate",
    "ResidentResponse",
    "ResidentBlock",
    "ResidentSetDefaulter",
    "ResidentMoveOut",
    "ResidentTransferUnit",
    "ResidentEnableAccess",
    "ResidentFilter",
    "ResidentListResponse",
    "ResidentStats",
    "ResidentSearch",
    # Vehicle
    "VehicleBase",
    "VehicleCreate",
    "VehicleUpdate",
    "VehicleResponse",
    "VehicleBlock",
    "VehicleAssignParking",
    "VehicleFilter",
    "VehicleListResponse",
    "VehicleStats",
    # Pet
    "PetBase",
    "PetCreate",
    "PetUpdate",
    "PetResponse",
    "PetUpdateVaccination",
    "PetFilter",
    "PetListResponse",
    "PetStats",
    # Dependent
    "DependentBase",
    "DependentCreate",
    "DependentUpdate",
    "DependentResponse",
    "DependentBlock",
    "DependentSetTemporary",
    "DependentAddPickupPerson",
    "DependentFilter",
    "DependentListResponse",
    "DependentStats",
    # Emergency Contact
    "EmergencyContactBase",
    "EmergencyContactCreate",
    "EmergencyContactUpdate",
    "EmergencyContactResponse",
    "EmergencyContactFilter",
    "EmergencyContactListResponse",
]
