"""
Schemas Pydantic para integrações governamentais.
"""

from .common import StandardResponse
from .ecac import (
    CertidaoResponse,
    ConsultaDebitosRequest,
    ConsultaDeclaracoesRequest,
    ConsultaParcelamentosRequest,
    ConsultaProcessosRequest,
    ConsultaSituacaoFiscalRequest,
    DebitoFiscalResponse,
    DeclaracaoResponse,
    EmitirCertidaoRequest,
    ParcelamentoResponse,
    ProcessoResponse,
    SimulacaoParcelamentoResponse,
    SimularParcelamentoRequest,
    SituacaoDebitoEnum,
    SituacaoFiscalEnum,
    SituacaoFiscalResponse,
    SituacaoProcessoEnum,
    StatusEcacResponse,
    TipoCertidaoEnum,
    TipoDeclaracaoEnum,
    TipoPendenciaEnum,
    ValidacaoCertidaoResponse,
    ValidarCertidaoRequest,
)
from .efd_reinf import (
    EventoResponse,
    GerarR1000Request,
    GerarR2010Request,
    GerarR2099Request,
    GerarR4010Request,
    GerarR4020Request,
    LoteResponse,
    PagamentoPFRequest,
    PagamentoPJRequest,
    R1000Response,
    R2010Response,
    R4010Response,
    R4020Response,
    RetencaoServicoRequest,
    StatusReinfResponse,
)
from .esocial import ESocialEventRequest
from .fgts_inss import CalculoFGTSRequest, CalculoINSSRequest
from .govbr import (
    AmbienteGovBrEnum,
    EmpresaVinculadaResponse,
    GerarUrlAutorizacaoRequest,
    GerarUrlLogoutRequest,
    NivelAutenticacaoEnum,
    ObterDadosUsuarioRequest,
    ObterEmpresasRequest,
    RenovarTokenRequest,
    StatusGovBrResponse,
    TipoDocumentoEnum,
    TokenGovBrResponse,
    TrocarCodigoRequest,
    UrlAutorizacaoResponse,
    UsuarioGovBrResponse,
    ValidacaoTokenResponse,
    ValidarTokenRequest,
)
from .nfce import (
    ConsumidorNFCe,
    ItemNFCe,
    NFCeCancelamentoRequest,
    NFCeConsultaRequest,
    NFCeContingenciaRequest,
    NFCeDANFERequest,
    NFCeEmissaoRequest,
    NFCeInutilizacaoRequest,
    NFCeResponse,
    NFCeResumoResponse,
    NFCeStatusServicoResponse,
    PagamentoNFCe,
    TipoPagamentoNFCe,
)
from .nfse_manaus import (
    CancelarNFSeRequest,
    CancelarNFSeResponse,
    ConsultarNFSeResponse,
    ConsultarNFSeRpsRequest,
    EmitirNFSeRequest,
    EmitirNFSeResponse,
    ServicoRequest,
    SubstituirNFSeRequest,
    TomadorRequest,
    ValidarConexaoResponse,
)
from .nfse_nacional import (
    AmbienteNacionalEnum,
    CancelarNFSeNacionalRequest,
    CancelarNFSeNacionalResponse,
    ComparacaoPadroesResponse,
    ConsultarDPSRequest,
    ConsultarNFSeNacionalRequest,
    ConsultarNFSeNacionalResponse,
    DPSStatusEnum,
    EmitirDPSRequest,
    EmitirDPSResponse,
    EventoNFSeResponse,
    MapeamentoServicoResponse,
    MotivoCancelamentoEnum,
    PrestadorNacionalRequest,
    RegimeEspecialEnum,
    ServicoNacionalRequest,
    StatusConexaoNacionalResponse,
    StatusMigracaoResponse,
    SubstituirNFSeNacionalRequest,
    TipoTributacaoEnum,
    TomadorNacionalRequest,
)
from .receita_federal import (
    ConsultaCNPJRequest,
    ConsultaCPFRequest,
    ValidateDocumentRequest,
)
from .sefaz import NFERequest

__all__ = [
    # Common
    "StandardResponse",
    # Receita Federal
    "ValidateDocumentRequest",
    "ConsultaCPFRequest",
    "ConsultaCNPJRequest",
    # FGTS/INSS
    "CalculoFGTSRequest",
    "CalculoINSSRequest",
    # eSocial
    "ESocialEventRequest",
    # SEFAZ
    "NFERequest",
    # NFS-e Manaus
    "EmitirNFSeRequest",
    "EmitirNFSeResponse",
    "ConsultarNFSeRpsRequest",
    "ConsultarNFSeResponse",
    "CancelarNFSeRequest",
    "CancelarNFSeResponse",
    "SubstituirNFSeRequest",
    "ValidarConexaoResponse",
    "TomadorRequest",
    "ServicoRequest",
    # EFD-Reinf
    "GerarR1000Request",
    "GerarR2010Request",
    "GerarR4010Request",
    "GerarR4020Request",
    "GerarR2099Request",
    "RetencaoServicoRequest",
    "PagamentoPFRequest",
    "PagamentoPJRequest",
    "EventoResponse",
    "R1000Response",
    "R2010Response",
    "R4010Response",
    "R4020Response",
    "LoteResponse",
    "StatusReinfResponse",
    # e-CAC
    "ConsultaSituacaoFiscalRequest",
    "ConsultaDebitosRequest",
    "ConsultaDeclaracoesRequest",
    "EmitirCertidaoRequest",
    "ValidarCertidaoRequest",
    "ConsultaParcelamentosRequest",
    "SimularParcelamentoRequest",
    "ConsultaProcessosRequest",
    "TipoCertidaoEnum",
    "SituacaoFiscalEnum",
    "TipoPendenciaEnum",
    "TipoDeclaracaoEnum",
    "SituacaoDebitoEnum",
    "SituacaoProcessoEnum",
    "SituacaoFiscalResponse",
    "CertidaoResponse",
    "ValidacaoCertidaoResponse",
    "DeclaracaoResponse",
    "ParcelamentoResponse",
    "SimulacaoParcelamentoResponse",
    "ProcessoResponse",
    "DebitoFiscalResponse",
    "StatusEcacResponse",
    # Gov.br
    "GerarUrlAutorizacaoRequest",
    "TrocarCodigoRequest",
    "RenovarTokenRequest",
    "ObterDadosUsuarioRequest",
    "ValidarTokenRequest",
    "GerarUrlLogoutRequest",
    "ObterEmpresasRequest",
    "NivelAutenticacaoEnum",
    "AmbienteGovBrEnum",
    "TipoDocumentoEnum",
    "UrlAutorizacaoResponse",
    "TokenGovBrResponse",
    "UsuarioGovBrResponse",
    "ValidacaoTokenResponse",
    "EmpresaVinculadaResponse",
    "StatusGovBrResponse",
    # NFS-e Padrao Nacional
    "AmbienteNacionalEnum",
    "TipoTributacaoEnum",
    "RegimeEspecialEnum",
    "MotivoCancelamentoEnum",
    "DPSStatusEnum",
    "PrestadorNacionalRequest",
    "TomadorNacionalRequest",
    "ServicoNacionalRequest",
    "EmitirDPSRequest",
    "EmitirDPSResponse",
    "ConsultarDPSRequest",
    "ConsultarNFSeNacionalRequest",
    "ConsultarNFSeNacionalResponse",
    "CancelarNFSeNacionalRequest",
    "CancelarNFSeNacionalResponse",
    "SubstituirNFSeNacionalRequest",
    "StatusMigracaoResponse",
    "ComparacaoPadroesResponse",
    "MapeamentoServicoResponse",
    "StatusConexaoNacionalResponse",
    "EventoNFSeResponse",
    # NFC-e
    "TipoPagamentoNFCe",
    "ConsumidorNFCe",
    "ItemNFCe",
    "PagamentoNFCe",
    "NFCeEmissaoRequest",
    "NFCeConsultaRequest",
    "NFCeCancelamentoRequest",
    "NFCeInutilizacaoRequest",
    "NFCeContingenciaRequest",
    "NFCeDANFERequest",
    "NFCeResponse",
    "NFCeStatusServicoResponse",
    "NFCeResumoResponse",
]
