/**
 * Applications Hooks - Gestão de Candidaturas
 *
 * Re-exports dos hooks Orval do módulo recruitment
 */

import {
  useListApplicationsApiV1RecruitmentApplicationsGet,
  useCreateApplicationApiV1RecruitmentApplicationsPost,
  useGetApplicationApiV1RecruitmentApplicationsApplicationIdGet,
  useUpdateApplicationApiV1RecruitmentApplicationsApplicationIdPatch,
  useDeleteApplicationApiV1RecruitmentApplicationsApplicationIdDelete,
  useListByCandidateApiV1RecruitmentApplicationsCandidateCandidateIdGet,
  useListByPositionApiV1RecruitmentApplicationsPositionPositionIdGet,
  useListActiveApiV1RecruitmentApplicationsActiveGet,
  useGetApplicationStatsApiV1RecruitmentApplicationsStatsGet,
  useAdvanceApplicationApiV1RecruitmentApplicationsApplicationIdAdvancePost,
  useRejectApplicationApiV1RecruitmentApplicationsApplicationIdRejectPost,
  useSendProposalApiV1RecruitmentApplicationsApplicationIdSendProposalPost,
  useAcceptProposalApiV1RecruitmentApplicationsApplicationIdAcceptProposalPost,
  useHireApplicationApiV1RecruitmentApplicationsApplicationIdHirePost,
  useBulkActionApiV1RecruitmentApplicationsBulkActionPost,
} from '@/types/generated/recruitment/recruitment-recrutamento-e-selecao/recruitment-recrutamento-e-selecao';

// List & Read
export const useApplications = useListApplicationsApiV1RecruitmentApplicationsGet;
export const useApplication = useGetApplicationApiV1RecruitmentApplicationsApplicationIdGet;
export const useApplicationsByCandidate = useListByCandidateApiV1RecruitmentApplicationsCandidateCandidateIdGet;
export const useApplicationsByPosition = useListByPositionApiV1RecruitmentApplicationsPositionPositionIdGet;
export const useActiveApplications = useListActiveApiV1RecruitmentApplicationsActiveGet;
export const useApplicationStats = useGetApplicationStatsApiV1RecruitmentApplicationsStatsGet;

// Mutations
export const useCreateApplication = useCreateApplicationApiV1RecruitmentApplicationsPost;
export const useUpdateApplication = useUpdateApplicationApiV1RecruitmentApplicationsApplicationIdPatch;
export const useDeleteApplication = useDeleteApplicationApiV1RecruitmentApplicationsApplicationIdDelete;
export const useAdvanceApplication = useAdvanceApplicationApiV1RecruitmentApplicationsApplicationIdAdvancePost;
export const useRejectApplication = useRejectApplicationApiV1RecruitmentApplicationsApplicationIdRejectPost;
export const useSendProposal = useSendProposalApiV1RecruitmentApplicationsApplicationIdSendProposalPost;
export const useAcceptProposal = useAcceptProposalApiV1RecruitmentApplicationsApplicationIdAcceptProposalPost;
export const useHireApplication = useHireApplicationApiV1RecruitmentApplicationsApplicationIdHirePost;
export const useBulkAction = useBulkActionApiV1RecruitmentApplicationsBulkActionPost;

// Re-export types
export type {
  ApplicationCreate,
  ApplicationUpdate,
  ApplicationResponse,
  ApplicationAdvance,
  ApplicationReject,
  ApplicationProposal,
  ApplicationHire,
  ApplicationBulkAction,
  ApplicationStats,
  ApplicationListResponse,
} from '@/types/generated/recruitment/conectaPROMóduloRECRUITMENT.schemas';
