"""Schemas do módulo de Integração REP."""

from .rep_device import (
    REPDeviceBase,
    REPDeviceCreate,
    REPDeviceUpdate,
    REPDeviceResponse,
    REPDeviceList,
    REPDeviceFilter,
    REPDeviceStatusUpdate,
    REPDeviceCredentials,
    REPDeviceTestConnection,
)
from .rep_event import (
    REPEventBase,
    REPEventCreate,
    REPEventUpdate,
    REPEventResponse,
    REPEventList,
    REPEventFilter,
    REPEventBulkCreate,
    REPEventProcess,
    REPEventProcessResult,
    REPEventWebhook,
    REPEventStats,
)
from .rep_sync import (
    REPSyncBase,
    REPSyncCreate,
    REPSyncUpdate,
    REPSyncResponse,
    REPSyncList,
    REPSyncFilter,
    REPSyncStart,
    REPSyncProgress,
    REPSyncResult,
    REPSyncSchedule,
)
from .afd_record import (
    AFDRecordBase,
    AFDRecordCreate,
    AFDRecordResponse,
    AFDRecordList,
    AFDRecordFilter,
    AFDExportRequest,
    AFDExportResponse,
    AFDValidationResult,
    AFDImportRequest,
    AFDImportResponse,
)

__all__ = [
    # REPDevice
    "REPDeviceBase",
    "REPDeviceCreate",
    "REPDeviceUpdate",
    "REPDeviceResponse",
    "REPDeviceList",
    "REPDeviceFilter",
    "REPDeviceStatusUpdate",
    "REPDeviceCredentials",
    "REPDeviceTestConnection",
    # REPEvent
    "REPEventBase",
    "REPEventCreate",
    "REPEventUpdate",
    "REPEventResponse",
    "REPEventList",
    "REPEventFilter",
    "REPEventBulkCreate",
    "REPEventProcess",
    "REPEventProcessResult",
    "REPEventWebhook",
    "REPEventStats",
    # REPSync
    "REPSyncBase",
    "REPSyncCreate",
    "REPSyncUpdate",
    "REPSyncResponse",
    "REPSyncList",
    "REPSyncFilter",
    "REPSyncStart",
    "REPSyncProgress",
    "REPSyncResult",
    "REPSyncSchedule",
    # AFDRecord
    "AFDRecordBase",
    "AFDRecordCreate",
    "AFDRecordResponse",
    "AFDRecordList",
    "AFDRecordFilter",
    "AFDExportRequest",
    "AFDExportResponse",
    "AFDValidationResult",
    "AFDImportRequest",
    "AFDImportResponse",
]
