"""Schemas do módulo Analytics Dashboard."""

from .dashboard_config import (
    DashboardConfigBase,
    DashboardConfigCreate,
    DashboardConfigUpdate,
    DashboardConfigResponse,
    DashboardListResponse,
    DashboardShare,
    DashboardCloneRequest,
    DashboardExport,
    DashboardImport,
)
from .dashboard_widget import (
    DashboardWidgetBase,
    DashboardWidgetCreate,
    DashboardWidgetUpdate,
    DashboardWidgetResponse,
    WidgetPosition,
    WidgetThreshold,
    WidgetChartConfig,
    WidgetPositionUpdate,
    WidgetBatchPositionUpdate,
    WidgetDataRequest,
    WidgetDataResponse,
    WidgetPreviewRequest,
)
from .kpi_definition import (
    KPIDefinitionBase,
    KPIDefinitionCreate,
    KPIDefinitionUpdate,
    KPIDefinitionResponse,
    KPIValueRequest,
    KPIValueResponse,
    KPITrend,
    KPIComparison,
    KPIDashboardResponse,
    KPIHistoryRequest,
    KPIHistoryPoint,
    KPIHistoryResponse,
    KPIAlertConfig,
)
from .scheduled_report import (
    ScheduledReportBase,
    ScheduledReportCreate,
    ScheduledReportUpdate,
    ScheduledReportResponse,
    ReportRunRequest,
    ReportRunResponse,
    ReportHistoryItem,
    ReportHistoryResponse,
    ReportTemplateCreate,
    ReportTemplateResponse,
)

__all__ = [
    # Dashboard Config
    "DashboardConfigBase",
    "DashboardConfigCreate",
    "DashboardConfigUpdate",
    "DashboardConfigResponse",
    "DashboardListResponse",
    "DashboardShare",
    "DashboardCloneRequest",
    "DashboardExport",
    "DashboardImport",
    # Dashboard Widget
    "DashboardWidgetBase",
    "DashboardWidgetCreate",
    "DashboardWidgetUpdate",
    "DashboardWidgetResponse",
    "WidgetPosition",
    "WidgetThreshold",
    "WidgetChartConfig",
    "WidgetPositionUpdate",
    "WidgetBatchPositionUpdate",
    "WidgetDataRequest",
    "WidgetDataResponse",
    "WidgetPreviewRequest",
    # KPI Definition
    "KPIDefinitionBase",
    "KPIDefinitionCreate",
    "KPIDefinitionUpdate",
    "KPIDefinitionResponse",
    "KPIValueRequest",
    "KPIValueResponse",
    "KPITrend",
    "KPIComparison",
    "KPIDashboardResponse",
    "KPIHistoryRequest",
    "KPIHistoryPoint",
    "KPIHistoryResponse",
    "KPIAlertConfig",
    # Scheduled Report
    "ScheduledReportBase",
    "ScheduledReportCreate",
    "ScheduledReportUpdate",
    "ScheduledReportResponse",
    "ReportRunRequest",
    "ReportRunResponse",
    "ReportHistoryItem",
    "ReportHistoryResponse",
    "ReportTemplateCreate",
    "ReportTemplateResponse",
]
