"""Schemas do modulo financeiro - Contas a Pagar, Contas a Receber, Fluxo de Caixa e Compras."""

# Contas a Pagar
from modules.financial.schemas.category import (
    PayableCategoryCreate,
    PayableCategoryFilter,
    PayableCategoryListResponse,
    PayableCategoryResponse,
    PayableCategoryTreeResponse,
    PayableCategoryUpdate,
)
from modules.financial.schemas.payable import (
    PayableAccountCreate,
    PayableAccountFilter,
    PayableAccountListResponse,
    PayableAccountResponse,
    PayableAccountStats,
    PayableAccountUpdate,
    PayableBulkApproveRequest,
    PayableBulkPaymentRequest,
    PayableInstallmentCreate,
    PayableInstallmentRenegotiateRequest,
    PayableInstallmentResponse,
    PayableInstallmentUpdate,
    PayablePaymentCreate,
    PayablePaymentReconcileRequest,
    PayablePaymentResponse,
    PayablePaymentReverseRequest,
    PayablePaymentUpdate,
    PayableScheduleRequest,
)
from modules.financial.schemas.payment_method import (
    PaymentMethodCreate,
    PaymentMethodListResponse,
    PaymentMethodResponse,
    PaymentMethodUpdate,
)
from modules.financial.schemas.supplier import (
    SupplierBlockRequest,
    SupplierCreate,
    SupplierFilter,
    SupplierListResponse,
    SupplierQualifyRequest,
    SupplierResponse,
    SupplierStats,
    SupplierUpdate,
)

# Contas a Receber
from modules.financial.schemas.receivable import (
    BillingRuleCreate,
    BillingRuleFilter,
    BillingRuleResponse,
    BillingRuleUpdate,
    CustomerCreate,
    CustomerFilter,
    CustomerResponse,
    CustomerUpdate,
    ReceivableAccountCreate,
    ReceivableAccountFilter,
    ReceivableAccountListResponse,
    ReceivableAccountResponse,
    ReceivableAccountStats,
    ReceivableAccountUpdate,
    ReceivableAgreementRequest,
    ReceivableBulkBoletoRequest,
    ReceivableBulkNotifyRequest,
    ReceivableBulkPaymentRequest,
    ReceivableCategoryCreate,
    ReceivableCategoryResponse,
    ReceivableCategoryUpdate,
    ReceivableInstallmentBoletoRequest,
    ReceivableInstallmentCreate,
    ReceivableInstallmentPixRequest,
    ReceivableInstallmentRenegotiateRequest,
    ReceivableInstallmentResponse,
    ReceivableInstallmentUpdate,
    ReceivablePaymentCreate,
    ReceivablePaymentReconcileRequest,
    ReceivablePaymentResponse,
    ReceivablePaymentReverseRequest,
    ReceivablePaymentUpdate,
    ReceivableProtestRequest,
    ReceivableWriteOffRequest,
)

# Fluxo de Caixa
from modules.financial.schemas.cashflow import (
    AIForecastRequest,
    AIForecastResponse,
    AnomalyDetectionRequest,
    AnomalyDetectionResponse,
    BankAccountCreate,
    BankAccountFilter,
    BankAccountResponse,
    BankAccountStats,
    BankAccountUpdate,
    BankReconciliationCreate,
    BankReconciliationResponse,
    BankReconciliationUpdate,
    BankTransactionCreate,
    BankTransactionFilter,
    BankTransactionImport,
    BankTransactionResponse,
    BankTransactionUpdate,
    CashFlowDashboard,
    CashFlowEntryCreate,
    CashFlowEntryFilter,
    CashFlowEntryRealize,
    CashFlowEntryResponse,
    CashFlowEntryUpdate,
    CashFlowForecastCreate,
    CashFlowForecastFilter,
    CashFlowForecastResponse,
    CashFlowForecastUpdate,
    CashFlowProjection,
    CashFlowSummary,
    CashFlowTrend,
    ForecastActualsUpdate,
    ForecastOpportunity,
    ForecastRisk,
    OptimizationSuggestion,
    ReconciliationAdjustment,
    ReconciliationItemMatch,
    StatementImport,
    TransferRequest,
)

# Compras
from modules.financial.schemas.goods_receipt import (
    GoodsReceiptCreate,
    GoodsReceiptListResponse,
    GoodsReceiptResponse,
    GoodsReceiptUpdate,
    ReceiptApproveRequest,
    ReceiptDivergenceRequest,
    ReceiptFilter,
    ReceiptInspectionRequest,
    ReceiptItemCreate,
    ReceiptItemResponse,
    ReceiptItemUpdate,
    ReceiptRejectRequest,
    ReceiptSignRequest,
    ReceiptStats,
)
from modules.financial.schemas.product import (
    ProductBlockRequest,
    ProductCreate,
    ProductListResponse,
    ProductPriceHistory,
    ProductResponse,
    ProductStats,
    ProductUpdate,
)
from modules.financial.schemas.product_category import (
    ProductCategoryCreate,
    ProductCategoryListResponse,
    ProductCategoryResponse,
    ProductCategoryStats,
    ProductCategoryTreeResponse,
    ProductCategoryUpdate,
)
from modules.financial.schemas.purchase_approval import (
    ApprovalApproveRequest,
    ApprovalDelegateRequest,
    ApprovalFilter,
    ApprovalInfoProvideRequest,
    ApprovalInfoRequest,
    ApprovalRejectRequest,
    ApprovalStats,
    ApprovalWorkflowConfig,
    MyApprovalsResponse,
    PurchaseApprovalCreate,
    PurchaseApprovalListResponse,
    PurchaseApprovalResponse,
    PurchaseApprovalUpdate,
)
from modules.financial.schemas.purchase_order import (
    OrderApproveRequest,
    OrderCancelRequest,
    OrderFilter,
    OrderInvoiceRequest,
    OrderItemCreate,
    OrderItemResponse,
    OrderItemUpdate,
    OrderPaymentRequest,
    OrderReceiveRequest,
    OrderRejectRequest,
    OrderStats,
    PurchaseOrderCreate,
    PurchaseOrderListResponse,
    PurchaseOrderResponse,
    PurchaseOrderUpdate,
)
from modules.financial.schemas.purchase_quotation import (
    PurchaseQuotationCreate,
    PurchaseQuotationListResponse,
    PurchaseQuotationResponse,
    PurchaseQuotationUpdate,
    QuotationComparisonResponse,
    QuotationItemCreate,
    QuotationItemResponse,
    QuotationItemUpdate,
    QuotationRejectRequest,
    QuotationScoreRequest,
    QuotationSelectRequest,
    QuotationStats,
)
from modules.financial.schemas.purchase_requisition import (
    PurchaseRequisitionCreate,
    PurchaseRequisitionListResponse,
    PurchaseRequisitionResponse,
    PurchaseRequisitionUpdate,
    RequisitionApproveRequest,
    RequisitionCancelRequest,
    RequisitionFilter,
    RequisitionItemCreate,
    RequisitionItemResponse,
    RequisitionItemUpdate,
    RequisitionRejectRequest,
    RequisitionStats,
)

__all__ = [
    # === Contas a Pagar ===
    # Supplier
    "SupplierCreate",
    "SupplierUpdate",
    "SupplierResponse",
    "SupplierListResponse",
    "SupplierFilter",
    "SupplierStats",
    "SupplierBlockRequest",
    "SupplierQualifyRequest",
    # PaymentMethod
    "PaymentMethodCreate",
    "PaymentMethodUpdate",
    "PaymentMethodResponse",
    "PaymentMethodListResponse",
    # PayableCategory
    "PayableCategoryCreate",
    "PayableCategoryUpdate",
    "PayableCategoryResponse",
    "PayableCategoryListResponse",
    "PayableCategoryTreeResponse",
    "PayableCategoryFilter",
    # PayableAccount
    "PayableAccountCreate",
    "PayableAccountUpdate",
    "PayableAccountResponse",
    "PayableAccountListResponse",
    "PayableAccountFilter",
    "PayableAccountStats",
    # PayableInstallment
    "PayableInstallmentCreate",
    "PayableInstallmentUpdate",
    "PayableInstallmentResponse",
    "PayableInstallmentRenegotiateRequest",
    # PayablePayment
    "PayablePaymentCreate",
    "PayablePaymentUpdate",
    "PayablePaymentResponse",
    "PayablePaymentReverseRequest",
    "PayablePaymentReconcileRequest",
    # Bulk Operations (Payable)
    "PayableBulkPaymentRequest",
    "PayableBulkApproveRequest",
    "PayableScheduleRequest",
    # === Contas a Receber ===
    # Customer
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerResponse",
    "CustomerFilter",
    # ReceivableCategory
    "ReceivableCategoryCreate",
    "ReceivableCategoryUpdate",
    "ReceivableCategoryResponse",
    # ReceivableAccount
    "ReceivableAccountCreate",
    "ReceivableAccountUpdate",
    "ReceivableAccountResponse",
    "ReceivableAccountListResponse",
    "ReceivableAccountFilter",
    "ReceivableAccountStats",
    # ReceivableInstallment
    "ReceivableInstallmentCreate",
    "ReceivableInstallmentUpdate",
    "ReceivableInstallmentResponse",
    "ReceivableInstallmentRenegotiateRequest",
    "ReceivableInstallmentBoletoRequest",
    "ReceivableInstallmentPixRequest",
    # ReceivablePayment
    "ReceivablePaymentCreate",
    "ReceivablePaymentUpdate",
    "ReceivablePaymentResponse",
    "ReceivablePaymentReverseRequest",
    "ReceivablePaymentReconcileRequest",
    # BillingRule
    "BillingRuleCreate",
    "BillingRuleUpdate",
    "BillingRuleResponse",
    "BillingRuleFilter",
    # Bulk Operations (Receivable)
    "ReceivableBulkPaymentRequest",
    "ReceivableBulkBoletoRequest",
    "ReceivableBulkNotifyRequest",
    # Special Operations
    "ReceivableWriteOffRequest",
    "ReceivableProtestRequest",
    "ReceivableAgreementRequest",
    # === Fluxo de Caixa ===
    # BankAccount
    "BankAccountCreate",
    "BankAccountUpdate",
    "BankAccountResponse",
    "BankAccountFilter",
    "BankAccountStats",
    # BankTransaction
    "BankTransactionCreate",
    "BankTransactionUpdate",
    "BankTransactionResponse",
    "BankTransactionFilter",
    "BankTransactionImport",
    "TransferRequest",
    # BankReconciliation
    "BankReconciliationCreate",
    "BankReconciliationUpdate",
    "BankReconciliationResponse",
    "ReconciliationItemMatch",
    "ReconciliationAdjustment",
    "StatementImport",
    # CashFlowEntry
    "CashFlowEntryCreate",
    "CashFlowEntryUpdate",
    "CashFlowEntryResponse",
    "CashFlowEntryFilter",
    "CashFlowEntryRealize",
    # CashFlowForecast
    "CashFlowForecastCreate",
    "CashFlowForecastUpdate",
    "CashFlowForecastResponse",
    "CashFlowForecastFilter",
    "ForecastActualsUpdate",
    "ForecastRisk",
    "ForecastOpportunity",
    # Projections & Analytics
    "CashFlowProjection",
    "CashFlowSummary",
    "CashFlowTrend",
    "CashFlowDashboard",
    # AI
    "AIForecastRequest",
    "AIForecastResponse",
    "AnomalyDetectionRequest",
    "AnomalyDetectionResponse",
    "OptimizationSuggestion",
    # === Compras ===
    # ProductCategory
    "ProductCategoryCreate",
    "ProductCategoryUpdate",
    "ProductCategoryResponse",
    "ProductCategoryListResponse",
    "ProductCategoryTreeResponse",
    "ProductCategoryStats",
    # Product
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductListResponse",
    "ProductStats",
    "ProductBlockRequest",
    "ProductPriceHistory",
    # PurchaseRequisition
    "PurchaseRequisitionCreate",
    "PurchaseRequisitionUpdate",
    "PurchaseRequisitionResponse",
    "PurchaseRequisitionListResponse",
    "RequisitionItemCreate",
    "RequisitionItemUpdate",
    "RequisitionItemResponse",
    "RequisitionFilter",
    "RequisitionStats",
    "RequisitionApproveRequest",
    "RequisitionRejectRequest",
    "RequisitionCancelRequest",
    # PurchaseQuotation
    "PurchaseQuotationCreate",
    "PurchaseQuotationUpdate",
    "PurchaseQuotationResponse",
    "PurchaseQuotationListResponse",
    "QuotationItemCreate",
    "QuotationItemUpdate",
    "QuotationItemResponse",
    "QuotationStats",
    "QuotationSelectRequest",
    "QuotationRejectRequest",
    "QuotationScoreRequest",
    "QuotationComparisonResponse",
    # PurchaseOrder
    "PurchaseOrderCreate",
    "PurchaseOrderUpdate",
    "PurchaseOrderResponse",
    "PurchaseOrderListResponse",
    "OrderItemCreate",
    "OrderItemUpdate",
    "OrderItemResponse",
    "OrderFilter",
    "OrderStats",
    "OrderApproveRequest",
    "OrderRejectRequest",
    "OrderCancelRequest",
    "OrderReceiveRequest",
    "OrderInvoiceRequest",
    "OrderPaymentRequest",
    # GoodsReceipt
    "GoodsReceiptCreate",
    "GoodsReceiptUpdate",
    "GoodsReceiptResponse",
    "GoodsReceiptListResponse",
    "ReceiptItemCreate",
    "ReceiptItemUpdate",
    "ReceiptItemResponse",
    "ReceiptFilter",
    "ReceiptStats",
    "ReceiptInspectionRequest",
    "ReceiptApproveRequest",
    "ReceiptRejectRequest",
    "ReceiptDivergenceRequest",
    "ReceiptSignRequest",
    # PurchaseApproval
    "PurchaseApprovalCreate",
    "PurchaseApprovalUpdate",
    "PurchaseApprovalResponse",
    "PurchaseApprovalListResponse",
    "ApprovalFilter",
    "ApprovalStats",
    "ApprovalApproveRequest",
    "ApprovalRejectRequest",
    "ApprovalDelegateRequest",
    "ApprovalInfoRequest",
    "ApprovalInfoProvideRequest",
    "ApprovalWorkflowConfig",
    "MyApprovalsResponse",
]
