"""Schemas do modulo financeiro.

Contas a Pagar, Contas a Receber, Fluxo de Caixa, Compras e Estoque.
"""

# Contas a Pagar
# Fluxo de Caixa
# Contabilidade
from modules.financial.schemas.accounting_schemas import (
    AccountFilter,
    AccountingAccountCreate,
    AccountingAccountListResponse,
    AccountingAccountResponse,
    AccountingAccountUpdate,
    AccountingPeriodCreate,
    AccountingPeriodListResponse,
    AccountingPeriodResponse,
    AccountingPeriodUpdate,
    AccountStats,
    AccountTreeResponse,
    BalanceFilter,
    BalanceStats,
    ChartOfAccountsCreate,
    ChartOfAccountsListResponse,
    ChartOfAccountsResponse,
    ChartOfAccountsUpdate,
    ChartStats,
    CostCenterCreate,
    CostCenterListResponse,
    CostCenterResponse,
    CostCenterStats,
    CostCenterUpdate,
    JournalEntryApprovalRequest,
    JournalEntryCreate,
    JournalEntryLineCreate,
    JournalEntryLineResponse,
    JournalEntryListResponse,
    JournalEntryResponse,
    JournalEntryReversalRequest,
    JournalEntryUpdate,
    JournalFilter,
    JournalStats,
    PeriodCloseRequest,
    PeriodReopenRequest,
    PeriodStats,
    TrialBalanceCreate,
    TrialBalanceDetailResponse,
    TrialBalanceItemResponse,
    TrialBalanceListResponse,
    TrialBalanceResponse,
)
from modules.financial.schemas.cashflow import (
    AIForecastRequest,
    AIForecastResponse,
    AnomalyDetectionRequest,
    AnomalyDetectionResponse,
    BankAccountCreate,
    BankAccountFilter,
    BankAccountResponse,
    BankAccountStats,
    BankAccountUpdate,
    BankReconciliationCreate,
    BankReconciliationResponse,
    BankReconciliationUpdate,
    BankTransactionCreate,
    BankTransactionFilter,
    BankTransactionImport,
    BankTransactionResponse,
    BankTransactionUpdate,
    CashFlowDashboard,
    CashFlowEntryCreate,
    CashFlowEntryFilter,
    CashFlowEntryRealize,
    CashFlowEntryResponse,
    CashFlowEntryUpdate,
    CashFlowForecastCreate,
    CashFlowForecastFilter,
    CashFlowForecastResponse,
    CashFlowForecastUpdate,
    CashFlowProjection,
    CashFlowSummary,
    CashFlowTrend,
    ForecastActualsUpdate,
    ForecastOpportunity,
    ForecastRisk,
    OptimizationSuggestion,
    ReconciliationAdjustment,
    ReconciliationItemMatch,
    StatementImport,
    TransferRequest,
)
from modules.financial.schemas.category import (
    PayableCategoryCreate,
    PayableCategoryFilter,
    PayableCategoryListResponse,
    PayableCategoryResponse,
    PayableCategoryTreeResponse,
    PayableCategoryUpdate,
)

# Fiscal
from modules.financial.schemas.fiscal_schemas import (
    # Retencao Federal
    CalculoRetencaoRequest,
    CalculoRetencaoResponse,
    # CFOP
    CFOPCreate,
    CFOPFilter,
    CFOPListResponse,
    CFOPResponse,
    CFOPUpdate,
    # Simples Nacional / DAS
    DASCalcularRequest,
    DASCalcularResponse,
    # AI Fiscal
    FiscalAIAnalyseRequest,
    FiscalAIAnalyseResponse,
    FiscalAIOptimizeRequest,
    FiscalAIOptimizeResponse,
    FiscalAIPredictRequest,
    FiscalAIPredictResponse,
    # Stats
    FiscalDashboard,
    FiscalStats,
    # NCM
    NCMCreate,
    NCMFilter,
    NCMListResponse,
    NCMResponse,
    NCMUpdate,
    # NF-e
    NFeCancelarRequest,
    NFeCreate,
    NFeEmitirRequest,
    NFeEmitirResponse,
    NFeFilter,
    NFeInutilizarRequest,
    NFeItemCreate,
    NFeItemResponse,
    NFeListResponse,
    NFeResponse,
    NFeUpdate,
    # NFS-e
    NFSeCancelarRequest,
    NFSeCreate,
    NFSeEmitirRequest,
    NFSeEmitirResponse,
    NFSeFilter,
    NFSeListResponse,
    NFSeResponse,
    NFSeUpdate,
    # Obrigacao Fiscal
    ObrigacaoFilter,
    ObrigacaoFiscalCreate,
    ObrigacaoFiscalListResponse,
    ObrigacaoFiscalResponse,
    ObrigacaoFiscalUpdate,
    RetencaoFederalCreate,
    RetencaoFederalListResponse,
    RetencaoFederalResponse,
    RetencaoFederalUpdate,
    SimplesNacionalDASCreate,
    SimplesNacionalDASResponse,
    # SPED
    SPEDFileCreate,
    SPEDFileListResponse,
    SPEDFileResponse,
    SPEDFilter,
    SPEDGerarRequest,
    SPEDTransmitirRequest,
    SPEDValidarRequest,
    # SUFRAMA
    SUFRAMAConfigCreate,
    SUFRAMAConfigResponse,
    SUFRAMAOperacaoCreate,
    SUFRAMAOperacaoListResponse,
    SUFRAMAOperacaoResponse,
)

# Compras
from modules.financial.schemas.goods_receipt import (
    GoodsReceiptCreate,
    GoodsReceiptListResponse,
    GoodsReceiptResponse,
    GoodsReceiptUpdate,
    ReceiptApproveRequest,
    ReceiptDivergenceRequest,
    ReceiptFilter,
    ReceiptInspectionRequest,
    ReceiptItemCreate,
    ReceiptItemResponse,
    ReceiptItemUpdate,
    ReceiptRejectRequest,
    ReceiptSignRequest,
    ReceiptStats,
)

# Estoque
from modules.financial.schemas.inventory_schemas import (
    InventoryStats,
    MovementFilter,
    MovementStats,
    ReservationStats,
    StockFilter,
    StockInventoryCreate,
    StockInventoryItemCount,
    StockInventoryItemCreate,
    StockInventoryItemResponse,
    StockInventoryListResponse,
    StockInventoryResponse,
    StockInventoryUpdate,
    StockItemCreate,
    StockItemListResponse,
    StockItemResponse,
    StockItemUpdate,
    StockMovementCreate,
    StockMovementListResponse,
    StockMovementResponse,
    StockMovementUpdate,
    StockReservationCreate,
    StockReservationListResponse,
    StockReservationRelease,
    StockReservationResponse,
    StockReservationUpdate,
    StockStats,
    WarehouseCreate,
    WarehouseListResponse,
    WarehouseResponse,
    WarehouseStats,
    WarehouseUpdate,
)
from modules.financial.schemas.payable import (
    PayableAccountCreate,
    PayableAccountFilter,
    PayableAccountListResponse,
    PayableAccountResponse,
    PayableAccountStats,
    PayableAccountUpdate,
    PayableBulkApproveRequest,
    PayableBulkPaymentRequest,
    PayableInstallmentCreate,
    PayableInstallmentRenegotiateRequest,
    PayableInstallmentResponse,
    PayableInstallmentUpdate,
    PayablePaymentCreate,
    PayablePaymentReconcileRequest,
    PayablePaymentResponse,
    PayablePaymentReverseRequest,
    PayablePaymentUpdate,
    PayableScheduleRequest,
)
from modules.financial.schemas.payment_method import (
    PaymentMethodCreate,
    PaymentMethodListResponse,
    PaymentMethodResponse,
    PaymentMethodUpdate,
)
from modules.financial.schemas.product import (
    ProductBlockRequest,
    ProductCreate,
    ProductListResponse,
    ProductPriceHistory,
    ProductResponse,
    ProductStats,
    ProductUpdate,
)
from modules.financial.schemas.product_category import (
    ProductCategoryCreate,
    ProductCategoryListResponse,
    ProductCategoryResponse,
    ProductCategoryStats,
    ProductCategoryTreeResponse,
    ProductCategoryUpdate,
)
from modules.financial.schemas.purchase_approval import (
    ApprovalApproveRequest,
    ApprovalDelegateRequest,
    ApprovalFilter,
    ApprovalInfoProvideRequest,
    ApprovalInfoRequest,
    ApprovalRejectRequest,
    ApprovalStats,
    ApprovalWorkflowConfig,
    MyApprovalsResponse,
    PurchaseApprovalCreate,
    PurchaseApprovalListResponse,
    PurchaseApprovalResponse,
    PurchaseApprovalUpdate,
)
from modules.financial.schemas.purchase_order import (
    OrderApproveRequest,
    OrderCancelRequest,
    OrderFilter,
    OrderInvoiceRequest,
    OrderItemCreate,
    OrderItemResponse,
    OrderItemUpdate,
    OrderPaymentRequest,
    OrderReceiveRequest,
    OrderRejectRequest,
    OrderStats,
    PurchaseOrderCreate,
    PurchaseOrderListResponse,
    PurchaseOrderResponse,
    PurchaseOrderUpdate,
)
from modules.financial.schemas.purchase_quotation import (
    PurchaseQuotationCreate,
    PurchaseQuotationListResponse,
    PurchaseQuotationResponse,
    PurchaseQuotationUpdate,
    QuotationComparisonResponse,
    QuotationItemCreate,
    QuotationItemResponse,
    QuotationItemUpdate,
    QuotationRejectRequest,
    QuotationScoreRequest,
    QuotationSelectRequest,
    QuotationStats,
)
from modules.financial.schemas.purchase_requisition import (
    PurchaseRequisitionCreate,
    PurchaseRequisitionListResponse,
    PurchaseRequisitionResponse,
    PurchaseRequisitionUpdate,
    RequisitionApproveRequest,
    RequisitionCancelRequest,
    RequisitionFilter,
    RequisitionItemCreate,
    RequisitionItemResponse,
    RequisitionItemUpdate,
    RequisitionRejectRequest,
    RequisitionStats,
)

# Contas a Receber
from modules.financial.schemas.receivable import (
    BillingRuleCreate,
    BillingRuleFilter,
    BillingRuleResponse,
    BillingRuleUpdate,
    CustomerCreate,
    CustomerFilter,
    CustomerResponse,
    CustomerUpdate,
    ReceivableAccountCreate,
    ReceivableAccountFilter,
    ReceivableAccountListResponse,
    ReceivableAccountResponse,
    ReceivableAccountStats,
    ReceivableAccountUpdate,
    ReceivableAgreementRequest,
    ReceivableBulkBoletoRequest,
    ReceivableBulkNotifyRequest,
    ReceivableBulkPaymentRequest,
    ReceivableCategoryCreate,
    ReceivableCategoryResponse,
    ReceivableCategoryUpdate,
    ReceivableInstallmentBoletoRequest,
    ReceivableInstallmentCreate,
    ReceivableInstallmentPixRequest,
    ReceivableInstallmentRenegotiateRequest,
    ReceivableInstallmentResponse,
    ReceivableInstallmentUpdate,
    ReceivablePaymentCreate,
    ReceivablePaymentReconcileRequest,
    ReceivablePaymentResponse,
    ReceivablePaymentReverseRequest,
    ReceivablePaymentUpdate,
    ReceivableProtestRequest,
    ReceivableWriteOffRequest,
)
from modules.financial.schemas.supplier import (
    SupplierBlockRequest,
    SupplierCreate,
    SupplierFilter,
    SupplierListResponse,
    SupplierQualifyRequest,
    SupplierResponse,
    SupplierStats,
    SupplierUpdate,
)

__all__ = [
    # === Contas a Pagar ===
    # Supplier
    "SupplierCreate",
    "SupplierUpdate",
    "SupplierResponse",
    "SupplierListResponse",
    "SupplierFilter",
    "SupplierStats",
    "SupplierBlockRequest",
    "SupplierQualifyRequest",
    # PaymentMethod
    "PaymentMethodCreate",
    "PaymentMethodUpdate",
    "PaymentMethodResponse",
    "PaymentMethodListResponse",
    # PayableCategory
    "PayableCategoryCreate",
    "PayableCategoryUpdate",
    "PayableCategoryResponse",
    "PayableCategoryListResponse",
    "PayableCategoryTreeResponse",
    "PayableCategoryFilter",
    # PayableAccount
    "PayableAccountCreate",
    "PayableAccountUpdate",
    "PayableAccountResponse",
    "PayableAccountListResponse",
    "PayableAccountFilter",
    "PayableAccountStats",
    # PayableInstallment
    "PayableInstallmentCreate",
    "PayableInstallmentUpdate",
    "PayableInstallmentResponse",
    "PayableInstallmentRenegotiateRequest",
    # PayablePayment
    "PayablePaymentCreate",
    "PayablePaymentUpdate",
    "PayablePaymentResponse",
    "PayablePaymentReverseRequest",
    "PayablePaymentReconcileRequest",
    # Bulk Operations (Payable)
    "PayableBulkPaymentRequest",
    "PayableBulkApproveRequest",
    "PayableScheduleRequest",
    # === Contas a Receber ===
    # Customer
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerResponse",
    "CustomerFilter",
    # ReceivableCategory
    "ReceivableCategoryCreate",
    "ReceivableCategoryUpdate",
    "ReceivableCategoryResponse",
    # ReceivableAccount
    "ReceivableAccountCreate",
    "ReceivableAccountUpdate",
    "ReceivableAccountResponse",
    "ReceivableAccountListResponse",
    "ReceivableAccountFilter",
    "ReceivableAccountStats",
    # ReceivableInstallment
    "ReceivableInstallmentCreate",
    "ReceivableInstallmentUpdate",
    "ReceivableInstallmentResponse",
    "ReceivableInstallmentRenegotiateRequest",
    "ReceivableInstallmentBoletoRequest",
    "ReceivableInstallmentPixRequest",
    # ReceivablePayment
    "ReceivablePaymentCreate",
    "ReceivablePaymentUpdate",
    "ReceivablePaymentResponse",
    "ReceivablePaymentReverseRequest",
    "ReceivablePaymentReconcileRequest",
    # BillingRule
    "BillingRuleCreate",
    "BillingRuleUpdate",
    "BillingRuleResponse",
    "BillingRuleFilter",
    # Bulk Operations (Receivable)
    "ReceivableBulkPaymentRequest",
    "ReceivableBulkBoletoRequest",
    "ReceivableBulkNotifyRequest",
    # Special Operations
    "ReceivableWriteOffRequest",
    "ReceivableProtestRequest",
    "ReceivableAgreementRequest",
    # === Fluxo de Caixa ===
    # BankAccount
    "BankAccountCreate",
    "BankAccountUpdate",
    "BankAccountResponse",
    "BankAccountFilter",
    "BankAccountStats",
    # BankTransaction
    "BankTransactionCreate",
    "BankTransactionUpdate",
    "BankTransactionResponse",
    "BankTransactionFilter",
    "BankTransactionImport",
    "TransferRequest",
    # BankReconciliation
    "BankReconciliationCreate",
    "BankReconciliationUpdate",
    "BankReconciliationResponse",
    "ReconciliationItemMatch",
    "ReconciliationAdjustment",
    "StatementImport",
    # CashFlowEntry
    "CashFlowEntryCreate",
    "CashFlowEntryUpdate",
    "CashFlowEntryResponse",
    "CashFlowEntryFilter",
    "CashFlowEntryRealize",
    # CashFlowForecast
    "CashFlowForecastCreate",
    "CashFlowForecastUpdate",
    "CashFlowForecastResponse",
    "CashFlowForecastFilter",
    "ForecastActualsUpdate",
    "ForecastRisk",
    "ForecastOpportunity",
    # Projections & Analytics
    "CashFlowProjection",
    "CashFlowSummary",
    "CashFlowTrend",
    "CashFlowDashboard",
    # AI
    "AIForecastRequest",
    "AIForecastResponse",
    "AnomalyDetectionRequest",
    "AnomalyDetectionResponse",
    "OptimizationSuggestion",
    # === Compras ===
    # ProductCategory
    "ProductCategoryCreate",
    "ProductCategoryUpdate",
    "ProductCategoryResponse",
    "ProductCategoryListResponse",
    "ProductCategoryTreeResponse",
    "ProductCategoryStats",
    # Product
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductListResponse",
    "ProductStats",
    "ProductBlockRequest",
    "ProductPriceHistory",
    # PurchaseRequisition
    "PurchaseRequisitionCreate",
    "PurchaseRequisitionUpdate",
    "PurchaseRequisitionResponse",
    "PurchaseRequisitionListResponse",
    "RequisitionItemCreate",
    "RequisitionItemUpdate",
    "RequisitionItemResponse",
    "RequisitionFilter",
    "RequisitionStats",
    "RequisitionApproveRequest",
    "RequisitionRejectRequest",
    "RequisitionCancelRequest",
    # PurchaseQuotation
    "PurchaseQuotationCreate",
    "PurchaseQuotationUpdate",
    "PurchaseQuotationResponse",
    "PurchaseQuotationListResponse",
    "QuotationItemCreate",
    "QuotationItemUpdate",
    "QuotationItemResponse",
    "QuotationStats",
    "QuotationSelectRequest",
    "QuotationRejectRequest",
    "QuotationScoreRequest",
    "QuotationComparisonResponse",
    # PurchaseOrder
    "PurchaseOrderCreate",
    "PurchaseOrderUpdate",
    "PurchaseOrderResponse",
    "PurchaseOrderListResponse",
    "OrderItemCreate",
    "OrderItemUpdate",
    "OrderItemResponse",
    "OrderFilter",
    "OrderStats",
    "OrderApproveRequest",
    "OrderRejectRequest",
    "OrderCancelRequest",
    "OrderReceiveRequest",
    "OrderInvoiceRequest",
    "OrderPaymentRequest",
    # GoodsReceipt
    "GoodsReceiptCreate",
    "GoodsReceiptUpdate",
    "GoodsReceiptResponse",
    "GoodsReceiptListResponse",
    "ReceiptItemCreate",
    "ReceiptItemUpdate",
    "ReceiptItemResponse",
    "ReceiptFilter",
    "ReceiptStats",
    "ReceiptInspectionRequest",
    "ReceiptApproveRequest",
    "ReceiptRejectRequest",
    "ReceiptDivergenceRequest",
    "ReceiptSignRequest",
    # PurchaseApproval
    "PurchaseApprovalCreate",
    "PurchaseApprovalUpdate",
    "PurchaseApprovalResponse",
    "PurchaseApprovalListResponse",
    "ApprovalFilter",
    "ApprovalStats",
    "ApprovalApproveRequest",
    "ApprovalRejectRequest",
    "ApprovalDelegateRequest",
    "ApprovalInfoRequest",
    "ApprovalInfoProvideRequest",
    "ApprovalWorkflowConfig",
    "MyApprovalsResponse",
    # === Estoque ===
    # Warehouse
    "WarehouseCreate",
    "WarehouseUpdate",
    "WarehouseResponse",
    "WarehouseListResponse",
    "WarehouseStats",
    # StockItem
    "StockItemCreate",
    "StockItemUpdate",
    "StockItemResponse",
    "StockItemListResponse",
    "StockStats",
    "StockFilter",
    # StockMovement
    "StockMovementCreate",
    "StockMovementUpdate",
    "StockMovementResponse",
    "StockMovementListResponse",
    "MovementStats",
    "MovementFilter",
    # StockInventory
    "StockInventoryCreate",
    "StockInventoryUpdate",
    "StockInventoryResponse",
    "StockInventoryListResponse",
    "StockInventoryItemCreate",
    "StockInventoryItemCount",
    "StockInventoryItemResponse",
    "InventoryStats",
    # StockReservation
    "StockReservationCreate",
    "StockReservationUpdate",
    "StockReservationResponse",
    "StockReservationListResponse",
    "StockReservationRelease",
    "ReservationStats",
    # === Contabilidade ===
    # ChartOfAccounts
    "ChartOfAccountsCreate",
    "ChartOfAccountsUpdate",
    "ChartOfAccountsResponse",
    "ChartOfAccountsListResponse",
    "ChartStats",
    # AccountingAccount
    "AccountingAccountCreate",
    "AccountingAccountUpdate",
    "AccountingAccountResponse",
    "AccountingAccountListResponse",
    "AccountTreeResponse",
    "AccountStats",
    "AccountFilter",
    # CostCenter
    "CostCenterCreate",
    "CostCenterUpdate",
    "CostCenterResponse",
    "CostCenterListResponse",
    "CostCenterStats",
    # AccountingPeriod
    "AccountingPeriodCreate",
    "AccountingPeriodUpdate",
    "AccountingPeriodResponse",
    "AccountingPeriodListResponse",
    "PeriodCloseRequest",
    "PeriodReopenRequest",
    "PeriodStats",
    # JournalEntry
    "JournalEntryCreate",
    "JournalEntryUpdate",
    "JournalEntryResponse",
    "JournalEntryListResponse",
    "JournalEntryLineCreate",
    "JournalEntryLineResponse",
    "JournalEntryReversalRequest",
    "JournalEntryApprovalRequest",
    "JournalStats",
    "JournalFilter",
    # TrialBalance
    "TrialBalanceCreate",
    "TrialBalanceResponse",
    "TrialBalanceListResponse",
    "TrialBalanceDetailResponse",
    "TrialBalanceItemResponse",
    "BalanceStats",
    "BalanceFilter",
    # === Fiscal ===
    # CFOP
    "CFOPCreate",
    "CFOPUpdate",
    "CFOPResponse",
    "CFOPListResponse",
    "CFOPFilter",
    # NCM
    "NCMCreate",
    "NCMUpdate",
    "NCMResponse",
    "NCMListResponse",
    "NCMFilter",
    # Retencao Federal
    "RetencaoFederalCreate",
    "RetencaoFederalUpdate",
    "RetencaoFederalResponse",
    "RetencaoFederalListResponse",
    "CalculoRetencaoRequest",
    "CalculoRetencaoResponse",
    # NF-e
    "NFeCreate",
    "NFeUpdate",
    "NFeResponse",
    "NFeListResponse",
    "NFeFilter",
    "NFeItemCreate",
    "NFeItemResponse",
    "NFeEmitirRequest",
    "NFeEmitirResponse",
    "NFeCancelarRequest",
    "NFeInutilizarRequest",
    # NFS-e
    "NFSeCreate",
    "NFSeUpdate",
    "NFSeResponse",
    "NFSeListResponse",
    "NFSeFilter",
    "NFSeEmitirRequest",
    "NFSeEmitirResponse",
    "NFSeCancelarRequest",
    # SPED
    "SPEDFileCreate",
    "SPEDFileResponse",
    "SPEDFileListResponse",
    "SPEDFilter",
    "SPEDGerarRequest",
    "SPEDValidarRequest",
    "SPEDTransmitirRequest",
    # Obrigacao Fiscal
    "ObrigacaoFiscalCreate",
    "ObrigacaoFiscalUpdate",
    "ObrigacaoFiscalResponse",
    "ObrigacaoFiscalListResponse",
    "ObrigacaoFilter",
    # Simples Nacional / DAS
    "SimplesNacionalDASCreate",
    "SimplesNacionalDASResponse",
    "DASCalcularRequest",
    "DASCalcularResponse",
    # SUFRAMA
    "SUFRAMAConfigCreate",
    "SUFRAMAConfigResponse",
    "SUFRAMAOperacaoCreate",
    "SUFRAMAOperacaoResponse",
    "SUFRAMAOperacaoListResponse",
    # AI Fiscal
    "FiscalAIAnalyseRequest",
    "FiscalAIAnalyseResponse",
    "FiscalAIOptimizeRequest",
    "FiscalAIOptimizeResponse",
    "FiscalAIPredictRequest",
    "FiscalAIPredictResponse",
    # Stats
    "FiscalStats",
    "FiscalDashboard",
]
