"""Schemas do módulo Mobile Time Clock."""

from .geofence_zone import (
    Coordinate,
    GeofenceCheckRequest,
    GeofenceCheckResponse,
    GeofenceZoneBase,
    GeofenceZoneCreate,
    GeofenceZoneFilter,
    GeofenceZoneList,
    GeofenceZoneResponse,
    GeofenceZoneStats,
    GeofenceZoneUpdate,
)
from .mobile_checkin import (
    CheckInBiometric,
    CheckInConfirmation,
    CheckInLocation,
    CheckInPhoto,
    CheckInValidation,
    CheckInValidationResult,
    MobileCheckInBatch,
    MobileCheckInCreate,
    MobileCheckInFilter,
    MobileCheckInList,
    MobileCheckInOffline,
    MobileCheckInResponse,
    MobileCheckInReview,
    MobileCheckInStats,
)
from .mobile_device import (
    DeviceHeartbeat,
    DeviceLocationUpdate,
    MobileDeviceApprove,
    MobileDeviceBase,
    MobileDeviceBlock,
    MobileDeviceFilter,
    MobileDeviceList,
    MobileDeviceRegister,
    MobileDeviceResponse,
    MobileDeviceStats,
    MobileDeviceUpdate,
)
from .offline_queue import (
    OfflineQueueBatch,
    OfflineQueueCleanup,
    OfflineQueueCleanupResult,
    OfflineQueueFilter,
    OfflineQueueItemCreate,
    OfflineQueueList,
    OfflineQueueResponse,
    OfflineQueueRetry,
    OfflineQueueStats,
    SyncBatchResult,
    SyncResult,
)

__all__ = [
    # Mobile Device
    "MobileDeviceBase",
    "MobileDeviceRegister",
    "MobileDeviceUpdate",
    "MobileDeviceApprove",
    "MobileDeviceBlock",
    "MobileDeviceResponse",
    "MobileDeviceList",
    "MobileDeviceFilter",
    "MobileDeviceStats",
    "DeviceHeartbeat",
    "DeviceLocationUpdate",
    # Mobile CheckIn
    "CheckInLocation",
    "CheckInBiometric",
    "CheckInPhoto",
    "CheckInValidation",
    "MobileCheckInCreate",
    "MobileCheckInOffline",
    "MobileCheckInBatch",
    "MobileCheckInReview",
    "MobileCheckInResponse",
    "MobileCheckInList",
    "MobileCheckInFilter",
    "MobileCheckInStats",
    "CheckInValidationResult",
    "CheckInConfirmation",
    # Geofence Zone
    "Coordinate",
    "GeofenceZoneBase",
    "GeofenceZoneCreate",
    "GeofenceZoneUpdate",
    "GeofenceZoneResponse",
    "GeofenceZoneList",
    "GeofenceZoneFilter",
    "GeofenceCheckRequest",
    "GeofenceCheckResponse",
    "GeofenceZoneStats",
    # Offline Queue
    "OfflineQueueItemCreate",
    "OfflineQueueBatch",
    "OfflineQueueResponse",
    "OfflineQueueList",
    "OfflineQueueFilter",
    "OfflineQueueStats",
    "SyncResult",
    "SyncBatchResult",
    "OfflineQueueRetry",
    "OfflineQueueCleanup",
    "OfflineQueueCleanupResult",
]
