"""Schemas do módulo CRM."""

from .lead import (
    LeadCreate,
    LeadFilter,
    LeadListResponse,
    LeadResponse,
    LeadScoreUpdate,
    LeadStats,
    LeadStatusUpdate,
    LeadUpdate,
)
from .opportunity import (
    OpportunityClose,
    OpportunityCreate,
    OpportunityCreateFromLead,
    OpportunityFilter,
    OpportunityListResponse,
    OpportunityResponse,
    OpportunityStageUpdate,
    OpportunityUpdate,
    PipelineForecast,
    PipelineStats,
)
from .proposal import (
    ProposalApprovalRequest,
    ProposalApprovalResponse,
    ProposalClientResponse,
    ProposalCreate,
    ProposalCreateFromOpportunity,
    ProposalDetailResponse,
    ProposalFilter,
    ProposalItemCreate,
    ProposalItemResponse,
    ProposalItemUpdate,
    ProposalListResponse,
    ProposalResponse,
    ProposalSend,
    ProposalStats,
    ProposalStatusUpdate,
    ProposalTemplateCreate,
    ProposalTemplateResponse,
    ProposalTemplateUpdate,
    ProposalUpdate,
)

__all__ = [
    # Lead
    "LeadCreate",
    "LeadUpdate",
    "LeadResponse",
    "LeadListResponse",
    "LeadFilter",
    "LeadScoreUpdate",
    "LeadStatusUpdate",
    "LeadStats",
    # Opportunity
    "OpportunityCreate",
    "OpportunityCreateFromLead",
    "OpportunityUpdate",
    "OpportunityStageUpdate",
    "OpportunityClose",
    "OpportunityResponse",
    "OpportunityListResponse",
    "OpportunityFilter",
    "PipelineStats",
    "PipelineForecast",
    # Proposal
    "ProposalCreate",
    "ProposalCreateFromOpportunity",
    "ProposalUpdate",
    "ProposalStatusUpdate",
    "ProposalSend",
    "ProposalApprovalRequest",
    "ProposalClientResponse",
    "ProposalResponse",
    "ProposalDetailResponse",
    "ProposalListResponse",
    "ProposalFilter",
    "ProposalStats",
    # ProposalItem
    "ProposalItemCreate",
    "ProposalItemUpdate",
    "ProposalItemResponse",
    # ProposalTemplate
    "ProposalTemplateCreate",
    "ProposalTemplateUpdate",
    "ProposalTemplateResponse",
    # ProposalApproval
    "ProposalApprovalResponse",
]
