"""Schemas do módulo CRM."""

from .commission import (
    CommissionApprove,
    CommissionCalculateRequest,
    CommissionCreate,
    CommissionDetailResponse,
    CommissionFilter,
    CommissionListResponse,
    CommissionPaymentConfirm,
    CommissionPaymentCreate,
    CommissionPaymentResponse,
    CommissionRanking,
    CommissionResponse,
    CommissionRuleCreate,
    CommissionRuleListResponse,
    CommissionRuleResponse,
    CommissionRuleUpdate,
    CommissionStats,
    CommissionStatusUpdate,
    CommissionSummaryFilter,
    CommissionSummaryResponse,
    CommissionUpdate,
    SellerCommissionRuleCreate,
    SellerCommissionRuleResponse,
    SellerCommissionStats,
)
from .contract import (
    ContractAddendumCreate,
    ContractAddendumResponse,
    ContractAddendumSign,
    ContractCreate,
    ContractCreateFromOpportunity,
    ContractCreateFromProposal,
    ContractDetailResponse,
    ContractFilter,
    ContractItemCreate,
    ContractItemResponse,
    ContractItemUpdate,
    ContractListResponse,
    ContractRenewal,
    ContractResponse,
    ContractSLAReportApprove,
    ContractSLAReportCreate,
    ContractSLAReportResponse,
    ContractStats,
    ContractStatusUpdate,
    ContractTemplateApprove,
    ContractTemplateCreate,
    ContractTemplateListResponse,
    ContractTemplateResponse,
    ContractTemplateUpdate,
    ContractUpdate,
    SLAIndicatorResult,
)
from .lead import (
    LeadCreate,
    LeadFilter,
    LeadListResponse,
    LeadResponse,
    LeadScoreUpdate,
    LeadStats,
    LeadStatusUpdate,
    LeadUpdate,
)
from .opportunity import (
    OpportunityClose,
    OpportunityCreate,
    OpportunityCreateFromLead,
    OpportunityFilter,
    OpportunityListResponse,
    OpportunityResponse,
    OpportunityStageUpdate,
    OpportunityUpdate,
    PipelineForecast,
    PipelineStats,
)
from .proposal import (
    ProposalApprovalRequest,
    ProposalApprovalResponse,
    ProposalClientResponse,
    ProposalCreate,
    ProposalCreateFromOpportunity,
    ProposalDetailResponse,
    ProposalFilter,
    ProposalItemCreate,
    ProposalItemResponse,
    ProposalItemUpdate,
    ProposalListResponse,
    ProposalResponse,
    ProposalSend,
    ProposalStats,
    ProposalStatusUpdate,
    ProposalTemplateCreate,
    ProposalTemplateResponse,
    ProposalTemplateUpdate,
    ProposalUpdate,
)

__all__ = [
    # Lead
    "LeadCreate",
    "LeadUpdate",
    "LeadResponse",
    "LeadListResponse",
    "LeadFilter",
    "LeadScoreUpdate",
    "LeadStatusUpdate",
    "LeadStats",
    # Opportunity
    "OpportunityCreate",
    "OpportunityCreateFromLead",
    "OpportunityUpdate",
    "OpportunityStageUpdate",
    "OpportunityClose",
    "OpportunityResponse",
    "OpportunityListResponse",
    "OpportunityFilter",
    "PipelineStats",
    "PipelineForecast",
    # Proposal
    "ProposalCreate",
    "ProposalCreateFromOpportunity",
    "ProposalUpdate",
    "ProposalStatusUpdate",
    "ProposalSend",
    "ProposalApprovalRequest",
    "ProposalClientResponse",
    "ProposalResponse",
    "ProposalDetailResponse",
    "ProposalListResponse",
    "ProposalFilter",
    "ProposalStats",
    # ProposalItem
    "ProposalItemCreate",
    "ProposalItemUpdate",
    "ProposalItemResponse",
    # ProposalTemplate
    "ProposalTemplateCreate",
    "ProposalTemplateUpdate",
    "ProposalTemplateResponse",
    # ProposalApproval
    "ProposalApprovalResponse",
    # Commission
    "CommissionCreate",
    "CommissionUpdate",
    "CommissionStatusUpdate",
    "CommissionApprove",
    "CommissionCalculateRequest",
    "CommissionResponse",
    "CommissionDetailResponse",
    "CommissionListResponse",
    "CommissionFilter",
    "CommissionStats",
    # CommissionRule
    "CommissionRuleCreate",
    "CommissionRuleUpdate",
    "CommissionRuleResponse",
    "CommissionRuleListResponse",
    # SellerCommissionRule
    "SellerCommissionRuleCreate",
    "SellerCommissionRuleResponse",
    # CommissionPayment
    "CommissionPaymentCreate",
    "CommissionPaymentConfirm",
    "CommissionPaymentResponse",
    # CommissionSummary
    "CommissionSummaryResponse",
    "CommissionSummaryFilter",
    # Statistics
    "SellerCommissionStats",
    "CommissionRanking",
    # Contract
    "ContractCreate",
    "ContractCreateFromOpportunity",
    "ContractCreateFromProposal",
    "ContractUpdate",
    "ContractStatusUpdate",
    "ContractRenewal",
    "ContractResponse",
    "ContractDetailResponse",
    "ContractListResponse",
    "ContractFilter",
    "ContractStats",
    # ContractItem
    "ContractItemCreate",
    "ContractItemUpdate",
    "ContractItemResponse",
    # ContractTemplate
    "ContractTemplateCreate",
    "ContractTemplateUpdate",
    "ContractTemplateApprove",
    "ContractTemplateResponse",
    "ContractTemplateListResponse",
    # ContractAddendum
    "ContractAddendumCreate",
    "ContractAddendumSign",
    "ContractAddendumResponse",
    # ContractSLAReport
    "SLAIndicatorResult",
    "ContractSLAReportCreate",
    "ContractSLAReportApprove",
    "ContractSLAReportResponse",
]
