"""Schemas do Portal do Funcionário."""

from modules.hr.employee_portal.schemas.document import (
    DocumentAcknowledgeRequest,
    DocumentCreate,
    DocumentFilterRequest,
    DocumentListResponse,
    DocumentResponse,
    DocumentSignRequest,
    DocumentSummary,
    DocumentUpdate,
)
from modules.hr.employee_portal.schemas.notification import (
    NotificationCreate,
    NotificationListResponse,
    NotificationMarkReadRequest,
    NotificationPreferencesUpdate,
    NotificationResponse,
    NotificationSummary,
    UnreadCountResponse,
)
from modules.hr.employee_portal.schemas.payslip import (
    PaySlipContestRequest,
    PaySlipCreate,
    PaySlipDeductionItem,
    PaySlipEarningItem,
    PaySlipListResponse,
    PaySlipResponse,
    PaySlipSummary,
    PaySlipUpdate,
)
from modules.hr.employee_portal.schemas.preferences import (
    DashboardConfigSchema,
    DashboardSettingsUpdate,
    DeviceInfo,
    NotificationConfigSchema,
    PreferencesCreate,
    PreferencesResponse,
    PreferencesUpdate,
    PrivacyConfigSchema,
    PrivacySettingsUpdate,
    SecurityConfigSchema,
    ThemeConfigSchema,
    TwoFactorSetupResponse,
)
from modules.hr.employee_portal.schemas.vacation import (
    VacationApprovalRequest,
    VacationBalanceResponse,
    VacationCalculationRequest,
    VacationCalculationResponse,
    VacationPeriodCreate,
    VacationPeriodResponse,
    VacationPeriodSummary,
    VacationRequestCreate,
    VacationRequestListResponse,
    VacationRequestResponse,
    VacationRequestSummary,
    VacationRequestUpdate,
)

__all__ = [
    # PaySlip
    "PaySlipCreate",
    "PaySlipUpdate",
    "PaySlipResponse",
    "PaySlipSummary",
    "PaySlipListResponse",
    "PaySlipContestRequest",
    "PaySlipEarningItem",
    "PaySlipDeductionItem",
    # Vacation
    "VacationPeriodCreate",
    "VacationPeriodResponse",
    "VacationPeriodSummary",
    "VacationRequestCreate",
    "VacationRequestUpdate",
    "VacationRequestResponse",
    "VacationRequestSummary",
    "VacationRequestListResponse",
    "VacationApprovalRequest",
    "VacationBalanceResponse",
    "VacationCalculationRequest",
    "VacationCalculationResponse",
    # Document
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentSummary",
    "DocumentListResponse",
    "DocumentAcknowledgeRequest",
    "DocumentSignRequest",
    "DocumentFilterRequest",
    # Notification
    "NotificationCreate",
    "NotificationResponse",
    "NotificationSummary",
    "NotificationListResponse",
    "NotificationMarkReadRequest",
    "NotificationPreferencesUpdate",
    "UnreadCountResponse",
    # Preferences
    "PreferencesCreate",
    "PreferencesUpdate",
    "PreferencesResponse",
    "ThemeConfigSchema",
    "NotificationConfigSchema",
    "DashboardConfigSchema",
    "PrivacyConfigSchema",
    "SecurityConfigSchema",
    "PrivacySettingsUpdate",
    "DashboardSettingsUpdate",
    "DeviceInfo",
    "TwoFactorSetupResponse",
]
