"""Schemas do módulo GED (Gestão Eletrônica de Documentos)."""

from modules.ged.schemas.document import (
    DocumentApprovalRequest,
    DocumentBase,
    DocumentCreate,
    DocumentFilter,
    DocumentListResponse,
    DocumentMoveRequest,
    DocumentOCRResult,
    DocumentResponse,
    DocumentSearchRequest,
    DocumentStats,
    DocumentUpdate,
    DocumentUploadRequest,
)
from modules.ged.schemas.document_share import (
    DocumentShareAccessRequest,
    DocumentShareBase,
    DocumentShareCreate,
    DocumentShareFilter,
    DocumentShareLinkRequest,
    DocumentShareLinkResponse,
    DocumentShareListResponse,
    DocumentShareResponse,
    DocumentShareStats,
    DocumentShareUpdate,
)
from modules.ged.schemas.document_signature import (
    DocumentSignatureBase,
    DocumentSignatureCreate,
    DocumentSignatureFilter,
    DocumentSignatureListResponse,
    DocumentSignatureResponse,
    DocumentSignatureUpdate,
    SignatureBulkCreate,
    SignaturePositionRequest,
    SignatureRefusalRequest,
    SignatureReminderRequest,
    SignatureRequest,
    SignatureStats,
    SignatureVerifyRequest,
)
from modules.ged.schemas.document_tag import (
    DocumentTagAssignment,
    DocumentTagBase,
    DocumentTagBulkCreate,
    DocumentTagCreate,
    DocumentTagFilter,
    DocumentTagListResponse,
    DocumentTagResponse,
    DocumentTagStats,
    DocumentTagTreeNode,
    DocumentTagUpdate,
)
from modules.ged.schemas.document_version import (
    DocumentVersionBase,
    DocumentVersionCompare,
    DocumentVersionCreate,
    DocumentVersionListResponse,
    DocumentVersionResponse,
    DocumentVersionRestoreRequest,
)
from modules.ged.schemas.folder import (
    FolderBase,
    FolderCreate,
    FolderFilter,
    FolderListResponse,
    FolderPermissionRequest,
    FolderResponse,
    FolderStats,
    FolderTreeNode,
    FolderUpdate,
)

__all__ = [
    # Folder
    "FolderBase",
    "FolderCreate",
    "FolderUpdate",
    "FolderResponse",
    "FolderListResponse",
    "FolderFilter",
    "FolderTreeNode",
    "FolderPermissionRequest",
    "FolderStats",
    # Document
    "DocumentBase",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentListResponse",
    "DocumentFilter",
    "DocumentMoveRequest",
    "DocumentApprovalRequest",
    "DocumentSearchRequest",
    "DocumentStats",
    "DocumentUploadRequest",
    "DocumentOCRResult",
    # Version
    "DocumentVersionBase",
    "DocumentVersionCreate",
    "DocumentVersionResponse",
    "DocumentVersionListResponse",
    "DocumentVersionCompare",
    "DocumentVersionRestoreRequest",
    # Share
    "DocumentShareBase",
    "DocumentShareCreate",
    "DocumentShareUpdate",
    "DocumentShareResponse",
    "DocumentShareListResponse",
    "DocumentShareFilter",
    "DocumentShareLinkRequest",
    "DocumentShareLinkResponse",
    "DocumentShareAccessRequest",
    "DocumentShareStats",
    # Tag
    "DocumentTagBase",
    "DocumentTagCreate",
    "DocumentTagUpdate",
    "DocumentTagResponse",
    "DocumentTagListResponse",
    "DocumentTagFilter",
    "DocumentTagTreeNode",
    "DocumentTagAssignment",
    "DocumentTagBulkCreate",
    "DocumentTagStats",
    # Signature
    "DocumentSignatureBase",
    "DocumentSignatureCreate",
    "DocumentSignatureUpdate",
    "DocumentSignatureResponse",
    "DocumentSignatureListResponse",
    "DocumentSignatureFilter",
    "SignatureRequest",
    "SignatureRefusalRequest",
    "SignatureVerifyRequest",
    "SignatureBulkCreate",
    "SignatureReminderRequest",
    "SignatureStats",
    "SignaturePositionRequest",
]
