"""Schemas do módulo de Ponto Eletrônico."""

from .time_entry import (
    TimeEntryCreate,
    TimeEntryUpdate,
    TimeEntryResponse,
    TimeEntryListResponse,
    TimeEntryFilter,
    TimeEntryStats,
    TimeEntryDaySummary,
    TimeEntryManualAdjust,
    TimeEntryApproval,
)
from .work_schedule import (
    WorkScheduleCreate,
    WorkScheduleUpdate,
    WorkScheduleResponse,
    WorkScheduleListResponse,
    WorkScheduleFilter,
    WorkScheduleStats,
    WorkScheduleValidation,
    DailyScheduleEntry,
    AllowedLocation,
)
from .overtime import (
    OvertimeCreate,
    OvertimeUpdate,
    OvertimeResponse,
    OvertimeListResponse,
    OvertimeFilter,
    OvertimeStats,
    OvertimeSummary,
    OvertimePreApproval,
    OvertimeApproval,
    OvertimeRejection,
    OvertimeCompensation,
    OvertimePayment,
)
from .time_justification import (
    TimeJustificationCreate,
    TimeJustificationUpdate,
    TimeJustificationResponse,
    TimeJustificationListResponse,
    TimeJustificationFilter,
    TimeJustificationStats,
    TimeJustificationAnalysis,
    TimeJustificationApproval,
    TimeJustificationPartialApproval,
    TimeJustificationRejection,
    TimeJustificationVerification,
    AttachmentInfo,
    MedicalInfo,
)
from .time_sheet import (
    TimeSheetCreate,
    TimeSheetUpdate,
    TimeSheetResponse,
    TimeSheetListResponse,
    TimeSheetFilter,
    TimeSheetStats,
    TimeSheetRecalculate,
    TimeSheetEmployeeApproval,
    TimeSheetManagerApproval,
    TimeSheetHRApproval,
    TimeSheetReview,
    TimeSheetClose,
    TimeSheetPayroll,
    TimeSheetReopen,
    TimeSheetBatchAction,
    DailySummaryEntry,
    PendingIssue,
)

__all__ = [
    # TimeEntry
    "TimeEntryCreate",
    "TimeEntryUpdate",
    "TimeEntryResponse",
    "TimeEntryListResponse",
    "TimeEntryFilter",
    "TimeEntryStats",
    "TimeEntryDaySummary",
    "TimeEntryManualAdjust",
    "TimeEntryApproval",
    # WorkSchedule
    "WorkScheduleCreate",
    "WorkScheduleUpdate",
    "WorkScheduleResponse",
    "WorkScheduleListResponse",
    "WorkScheduleFilter",
    "WorkScheduleStats",
    "WorkScheduleValidation",
    "DailyScheduleEntry",
    "AllowedLocation",
    # Overtime
    "OvertimeCreate",
    "OvertimeUpdate",
    "OvertimeResponse",
    "OvertimeListResponse",
    "OvertimeFilter",
    "OvertimeStats",
    "OvertimeSummary",
    "OvertimePreApproval",
    "OvertimeApproval",
    "OvertimeRejection",
    "OvertimeCompensation",
    "OvertimePayment",
    # TimeJustification
    "TimeJustificationCreate",
    "TimeJustificationUpdate",
    "TimeJustificationResponse",
    "TimeJustificationListResponse",
    "TimeJustificationFilter",
    "TimeJustificationStats",
    "TimeJustificationAnalysis",
    "TimeJustificationApproval",
    "TimeJustificationPartialApproval",
    "TimeJustificationRejection",
    "TimeJustificationVerification",
    "AttachmentInfo",
    "MedicalInfo",
    # TimeSheet
    "TimeSheetCreate",
    "TimeSheetUpdate",
    "TimeSheetResponse",
    "TimeSheetListResponse",
    "TimeSheetFilter",
    "TimeSheetStats",
    "TimeSheetRecalculate",
    "TimeSheetEmployeeApproval",
    "TimeSheetManagerApproval",
    "TimeSheetHRApproval",
    "TimeSheetReview",
    "TimeSheetClose",
    "TimeSheetPayroll",
    "TimeSheetReopen",
    "TimeSheetBatchAction",
    "DailySummaryEntry",
    "PendingIssue",
]
