"""Schemas do módulo de Ponto Eletrônico."""

from .overtime import (
    OvertimeApproval,
    OvertimeCompensation,
    OvertimeCreate,
    OvertimeFilter,
    OvertimeListResponse,
    OvertimePayment,
    OvertimePreApproval,
    OvertimeRejection,
    OvertimeResponse,
    OvertimeStats,
    OvertimeSummary,
    OvertimeUpdate,
)
from .time_entry import (
    TimeEntryApproval,
    TimeEntryCreate,
    TimeEntryDaySummary,
    TimeEntryFilter,
    TimeEntryListResponse,
    TimeEntryManualAdjust,
    TimeEntryResponse,
    TimeEntryStats,
    TimeEntryUpdate,
)
from .time_justification import (
    AttachmentInfo,
    MedicalInfo,
    TimeJustificationAnalysis,
    TimeJustificationApproval,
    TimeJustificationCreate,
    TimeJustificationFilter,
    TimeJustificationListResponse,
    TimeJustificationPartialApproval,
    TimeJustificationRejection,
    TimeJustificationResponse,
    TimeJustificationStats,
    TimeJustificationUpdate,
    TimeJustificationVerification,
)
from .time_sheet import (
    DailySummaryEntry,
    PendingIssue,
    TimeSheetBatchAction,
    TimeSheetClose,
    TimeSheetCreate,
    TimeSheetEmployeeApproval,
    TimeSheetFilter,
    TimeSheetHRApproval,
    TimeSheetListResponse,
    TimeSheetManagerApproval,
    TimeSheetPayroll,
    TimeSheetRecalculate,
    TimeSheetReopen,
    TimeSheetResponse,
    TimeSheetReview,
    TimeSheetStats,
    TimeSheetUpdate,
)
from .work_schedule import (
    AllowedLocation,
    DailyScheduleEntry,
    WorkScheduleCreate,
    WorkScheduleFilter,
    WorkScheduleListResponse,
    WorkScheduleResponse,
    WorkScheduleStats,
    WorkScheduleUpdate,
    WorkScheduleValidation,
)

__all__ = [
    # TimeEntry
    "TimeEntryCreate",
    "TimeEntryUpdate",
    "TimeEntryResponse",
    "TimeEntryListResponse",
    "TimeEntryFilter",
    "TimeEntryStats",
    "TimeEntryDaySummary",
    "TimeEntryManualAdjust",
    "TimeEntryApproval",
    # WorkSchedule
    "WorkScheduleCreate",
    "WorkScheduleUpdate",
    "WorkScheduleResponse",
    "WorkScheduleListResponse",
    "WorkScheduleFilter",
    "WorkScheduleStats",
    "WorkScheduleValidation",
    "DailyScheduleEntry",
    "AllowedLocation",
    # Overtime
    "OvertimeCreate",
    "OvertimeUpdate",
    "OvertimeResponse",
    "OvertimeListResponse",
    "OvertimeFilter",
    "OvertimeStats",
    "OvertimeSummary",
    "OvertimePreApproval",
    "OvertimeApproval",
    "OvertimeRejection",
    "OvertimeCompensation",
    "OvertimePayment",
    # TimeJustification
    "TimeJustificationCreate",
    "TimeJustificationUpdate",
    "TimeJustificationResponse",
    "TimeJustificationListResponse",
    "TimeJustificationFilter",
    "TimeJustificationStats",
    "TimeJustificationAnalysis",
    "TimeJustificationApproval",
    "TimeJustificationPartialApproval",
    "TimeJustificationRejection",
    "TimeJustificationVerification",
    "AttachmentInfo",
    "MedicalInfo",
    # TimeSheet
    "TimeSheetCreate",
    "TimeSheetUpdate",
    "TimeSheetResponse",
    "TimeSheetListResponse",
    "TimeSheetFilter",
    "TimeSheetStats",
    "TimeSheetRecalculate",
    "TimeSheetEmployeeApproval",
    "TimeSheetManagerApproval",
    "TimeSheetHRApproval",
    "TimeSheetReview",
    "TimeSheetClose",
    "TimeSheetPayroll",
    "TimeSheetReopen",
    "TimeSheetBatchAction",
    "DailySummaryEntry",
    "PendingIssue",
]
