"""Schemas do módulo de Visitantes."""

from modules.visitors.schemas.visitor import (
    VisitorBase,
    VisitorBlock,
    VisitorBulkCreate,
    VisitorCreate,
    VisitorFilter,
    VisitorListResponse,
    VisitorResponse,
    VisitorSearch,
    VisitorStats,
    VisitorUpdate,
)
from modules.visitors.schemas.authorization import (
    AuthorizationApprove,
    AuthorizationBase,
    AuthorizationCreate,
    AuthorizationFilter,
    AuthorizationListResponse,
    AuthorizationReject,
    AuthorizationResponse,
    AuthorizationStats,
    AuthorizationUpdate,
    AuthorizationValidate,
    AuthorizationValidateResponse,
)
from modules.visitors.schemas.log import (
    LogBase,
    LogDeny,
    LogEntry,
    LogExit,
    LogFilter,
    LogListResponse,
    LogResponse,
    LogStats,
    LogTimeline,
    VisitorInside,
)
from modules.visitors.schemas.schedule import (
    ScheduleBase,
    ScheduleCalendar,
    ScheduleCancel,
    ScheduleConfirm,
    ScheduleCreate,
    ScheduleFilter,
    ScheduleListResponse,
    ScheduleReminder,
    ScheduleReschedule,
    ScheduleResponse,
    ScheduleStats,
    ScheduleUpdate,
)

__all__ = [
    # Visitor
    "VisitorBase",
    "VisitorCreate",
    "VisitorUpdate",
    "VisitorResponse",
    "VisitorListResponse",
    "VisitorBlock",
    "VisitorFilter",
    "VisitorStats",
    "VisitorBulkCreate",
    "VisitorSearch",
    # Authorization
    "AuthorizationBase",
    "AuthorizationCreate",
    "AuthorizationUpdate",
    "AuthorizationResponse",
    "AuthorizationListResponse",
    "AuthorizationApprove",
    "AuthorizationReject",
    "AuthorizationFilter",
    "AuthorizationStats",
    "AuthorizationValidate",
    "AuthorizationValidateResponse",
    # Log
    "LogBase",
    "LogEntry",
    "LogExit",
    "LogDeny",
    "LogResponse",
    "LogListResponse",
    "LogFilter",
    "LogStats",
    "LogTimeline",
    "VisitorInside",
    # Schedule
    "ScheduleBase",
    "ScheduleCreate",
    "ScheduleUpdate",
    "ScheduleResponse",
    "ScheduleListResponse",
    "ScheduleConfirm",
    "ScheduleCancel",
    "ScheduleReschedule",
    "ScheduleFilter",
    "ScheduleStats",
    "ScheduleCalendar",
    "ScheduleReminder",
]
