"""Schemas do módulo Recruitment."""

from .application import (
    ApplicationAdvance,
    ApplicationBase,
    ApplicationBulkAction,
    ApplicationCreate,
    ApplicationFilter,
    ApplicationHire,
    ApplicationListResponse,
    ApplicationProposal,
    ApplicationReject,
    ApplicationResponse,
    ApplicationStats,
    ApplicationUpdate,
)
from .candidate import (
    CandidateBase,
    CandidateBlock,
    CandidateCreate,
    CandidateFilter,
    CandidateImport,
    CandidateListResponse,
    CandidateResponse,
    CandidateStats,
    CandidateUpdate,
    LanguageInfo,
)
from .candidate_education import (
    CandidateEducationBase,
    CandidateEducationCreate,
    CandidateEducationFilter,
    CandidateEducationListResponse,
    CandidateEducationResponse,
    CandidateEducationUpdate,
    ExchangeInfo,
    ThesisInfo,
)
from .candidate_experience import (
    CandidateExperienceBase,
    CandidateExperienceCreate,
    CandidateExperienceFilter,
    CandidateExperienceListResponse,
    CandidateExperienceResponse,
    CandidateExperienceUpdate,
    ReferenceInfo,
)
from .candidate_skill import (
    CandidateSkillBase,
    CandidateSkillCreate,
    CandidateSkillFilter,
    CandidateSkillListResponse,
    CandidateSkillResponse,
    CandidateSkillUpdate,
    CertificationAdd,
)
from .interview import (
    InterviewBase,
    InterviewCalendar,
    InterviewCancel,
    InterviewComplete,
    InterviewCreate,
    InterviewEvaluation,
    InterviewFilter,
    InterviewListResponse,
    InterviewReschedule,
    InterviewResponse,
    InterviewSlot,
    InterviewStats,
    InterviewUpdate,
)
from .job_position import (
    JobPositionBase,
    JobPositionCreate,
    JobPositionFilter,
    JobPositionListResponse,
    JobPositionPublish,
    JobPositionResponse,
    JobPositionStats,
    JobPositionUpdate,
    SelectionStage,
)

__all__ = [
    # JobPosition
    "JobPositionBase",
    "JobPositionCreate",
    "JobPositionUpdate",
    "JobPositionResponse",
    "JobPositionListResponse",
    "JobPositionFilter",
    "JobPositionStats",
    "JobPositionPublish",
    "SelectionStage",
    # Candidate
    "CandidateBase",
    "CandidateCreate",
    "CandidateUpdate",
    "CandidateResponse",
    "CandidateListResponse",
    "CandidateFilter",
    "CandidateStats",
    "CandidateBlock",
    "CandidateImport",
    "LanguageInfo",
    # Application
    "ApplicationBase",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationResponse",
    "ApplicationListResponse",
    "ApplicationFilter",
    "ApplicationStats",
    "ApplicationAdvance",
    "ApplicationReject",
    "ApplicationProposal",
    "ApplicationHire",
    "ApplicationBulkAction",
    # Interview
    "InterviewBase",
    "InterviewCreate",
    "InterviewUpdate",
    "InterviewResponse",
    "InterviewListResponse",
    "InterviewFilter",
    "InterviewStats",
    "InterviewComplete",
    "InterviewReschedule",
    "InterviewCancel",
    "InterviewEvaluation",
    "InterviewSlot",
    "InterviewCalendar",
    # CandidateSkill
    "CandidateSkillBase",
    "CandidateSkillCreate",
    "CandidateSkillUpdate",
    "CandidateSkillResponse",
    "CandidateSkillListResponse",
    "CandidateSkillFilter",
    "CertificationAdd",
    # CandidateExperience
    "CandidateExperienceBase",
    "CandidateExperienceCreate",
    "CandidateExperienceUpdate",
    "CandidateExperienceResponse",
    "CandidateExperienceListResponse",
    "CandidateExperienceFilter",
    "ReferenceInfo",
    # CandidateEducation
    "CandidateEducationBase",
    "CandidateEducationCreate",
    "CandidateEducationUpdate",
    "CandidateEducationResponse",
    "CandidateEducationListResponse",
    "CandidateEducationFilter",
    "ThesisInfo",
    "ExchangeInfo",
]
